name: fleet
on:
  # NOTE: the repository_dispatch only triggers on the master branch, and it is not
  # possible to specify a branch
  repository_dispatch:
    types: [dispatch-test]
jobs:
  build:
    name: 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Run the test
        run: echo ${{ github.event.client_payload.foo }}

  dispatchTest:
    needs: build
    strategy:
      matrix:
        repo: ["karantan/go-instaaction"]
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: dispatch-test
          client-payload: '{"foo": "bar, baz"}'
